/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado del sistema
         * @description Informa si el backend está vivo y si su conexión con la base de datos
         *     está establecida **en el momento de la consulta** (no es un estado
         *     memorizado del arranque; spec FR-003).
         *
         *     - `200 OK`: el servicio está vivo y la base de datos conectada
         *       (sobre de éxito `SystemStatus`).
         *     - `503 Service Unavailable`: el servicio está vivo (sigue
         *       respondiendo, spec FR-004) pero la base de datos **no** está
         *       conectada (sobre de error `database_unavailable`, fallo previsible).
         *
         *     Distinción para el cliente: si la petición falla a nivel de red
         *     (sin respuesta HTTP), es el backend el que no está disponible.
         */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Sobre de éxito del endpoint de estado: informe del sistema en el
         *     momento de la consulta. F1 lo emite únicamente como `200`; si algo
         *     está degradado, la respuesta es un error con su sobre (p. ej. `503`
         *     `database_unavailable`), de modo que todo cliente maneja un solo
         *     formato de error (FR-012).
         */
        SystemStatus: {
            /**
             * @description Estado del proceso backend. En F1 el único valor posible es `ok`
             *     (un `200` siempre significa "servicio sano"). El campo se mantiene
             *     por FR-002 (la respuesta indica el estado del servicio) y admite
             *     valores futuros si se agregan más chequeos.
             * @constant
             */
            status: "ok";
            /**
             * @description Conexión con PostgreSQL establecida en el momento de la consulta
             *     (FR-003). El caso "no conectada" se comunica como `503` con
             *     `error.code = database_unavailable` y
             *     `error.details.database = "disconnected"`.
             * @constant
             */
            database: "connected";
        };
        /**
         * @description Sobre de error estándar de la API (FR-012/FR-013). Todo 4xx/5xx lo
         *     usa; es el único formato de error que quien consume debe implementar.
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            /**
             * @description Código estable y accionable de la API (snake_case). Registro cerrado;
             *     F1 puede emitir: `not_found`, `method_not_allowed`,
             *     `database_unavailable`, `internal`.
             * @enum {string}
             */
            code: "invalid" | "unauthenticated" | "forbidden" | "not_found" | "method_not_allowed" | "conflict" | "rate_limited" | "database_unavailable" | "internal";
            /**
             * @description Mensaje seguro y comprensible (español). Nunca contiene nombres
             *     internos, trazas de error, SQL ni datos de infraestructura (FR-013).
             *     Para `internal` es siempre el genérico "Error interno del servidor".
             * @example La base de datos no está conectada
             */
            message: string;
            /**
             * @description Detalle opcional y seguro: por campo en validaciones (F2+) o datos
             *     de diagnóstico del caso (p. ej. `{"database":"disconnected"}`).
             *     Nunca información interna del sistema.
             */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Ruta no documentada. El fallback del router responde este sobre (la stdlib respondería texto). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "not_found",
                 *         "message": "Recurso no encontrado"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Método no documentado para la ruta (p. ej. `POST /healthz`). */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "method_not_allowed",
                 *         "message": "Método no permitido"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Error inesperado. El mensaje es genérico a propósito (FR-013): el
         *     detalle interno queda registrado en el log estructurado con su
         *     `request_id` para diagnóstico.
         */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "internal",
                 *         "message": "Error interno del servidor"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Servicio vivo, base de datos NO conectada (fallo previsible de
         *     `/healthz`; FR-004). La respuesta llega en ≤2 s por el timeout del ping.
         */
        DatabaseUnavailable: {
            headers: {
                /** @description El estado nunca debe ser cacheado por intermediarios. */
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "database_unavailable",
                 *         "message": "La base de datos no está conectada",
                 *         "details": {
                 *           "database": "disconnected"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio vivo y base de datos conectada. */
            200: {
                headers: {
                    /** @description El estado nunca debe ser cacheado por intermediarios. */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "database": "connected"
                     *     }
                     */
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            500: components["responses"]["Internal"];
            503: components["responses"]["DatabaseUnavailable"];
        };
    };
}
