// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminActions = `-- name: CountAdminActions :one
SELECT count(*)::bigint AS total
FROM admin_actions aa
WHERE (
        $1::uuid IS NULL
        OR aa.actor_user_id = $1
        OR aa.target_user_id = $1
      )
  AND ($2::timestamptz IS NULL OR aa.created_at >= $2)
  AND ($3::timestamptz IS NULL OR aa.created_at < $3)
`

type CountAdminActionsParams struct {
	UserID pgtype.UUID
	From   pgtype.Timestamptz
	To     pgtype.Timestamptz
}

// Mismo filtro que `ListAdminActions` para que `total` corresponda a la página.
func (q *Queries) CountAdminActions(ctx context.Context, arg CountAdminActionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminActions, arg.UserID, arg.From, arg.To)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countLoginEvents = `-- name: CountLoginEvents :one
SELECT count(*)::bigint AS total
FROM login_events le
WHERE ($1::uuid IS NULL OR le.user_id = $1)
  AND ($2::timestamptz IS NULL OR le.created_at >= $2)
  AND ($3::timestamptz IS NULL OR le.created_at < $3)
`

type CountLoginEventsParams struct {
	UserID pgtype.UUID
	From   pgtype.Timestamptz
	To     pgtype.Timestamptz
}

// Mismo filtro que `ListLoginEvents` para que `total` corresponda a la página.
func (q *Queries) CountLoginEvents(ctx context.Context, arg CountLoginEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginEvents, arg.UserID, arg.From, arg.To)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertAdminAction = `-- name: InsertAdminAction :one
INSERT INTO admin_actions (
    actor_user_id,
    action,
    target_kind,
    target_user_id,
    target_role_id,
    target_label,
    result
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, actor_user_id, action, target_kind, target_user_id, target_role_id,
          target_label, result, created_at
`

type InsertAdminActionParams struct {
	ActorUserID  pgtype.UUID
	Action       string
	TargetKind   string
	TargetUserID pgtype.UUID
	TargetRoleID pgtype.UUID
	TargetLabel  pgtype.Text
	Result       string
}

type InsertAdminActionRow struct {
	ID           pgtype.UUID
	ActorUserID  pgtype.UUID
	Action       string
	TargetKind   string
	TargetUserID pgtype.UUID
	TargetRoleID pgtype.UUID
	TargetLabel  pgtype.Text
	Result       string
	CreatedAt    pgtype.Timestamptz
}

// Una fila por acción administrativa sensible, incluidos los intentos que fallan
// o se deniegan (FR-023). La inicialización (FR-007) deja `actor_user_id` NULL
// con `action = 'user.create'`, el único caso sin actor (CHECK de la tabla).
func (q *Queries) InsertAdminAction(ctx context.Context, arg InsertAdminActionParams) (InsertAdminActionRow, error) {
	row := q.db.QueryRow(ctx, insertAdminAction,
		arg.ActorUserID,
		arg.Action,
		arg.TargetKind,
		arg.TargetUserID,
		arg.TargetRoleID,
		arg.TargetLabel,
		arg.Result,
	)
	var i InsertAdminActionRow
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.TargetKind,
		&i.TargetUserID,
		&i.TargetRoleID,
		&i.TargetLabel,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const insertLoginEvent = `-- name: InsertLoginEvent :one

INSERT INTO login_events (user_id, result, ip)
VALUES ($1, $2, $3)
RETURNING id, user_id, result, ip, created_at
`

type InsertLoginEventParams struct {
	UserID pgtype.UUID
	Result string
	Ip     string
}

type InsertLoginEventRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Result    string
	Ip        string
	CreatedAt pgtype.Timestamptz
}

// Consultas de auditoría (FR-022…FR-025): historial de intentos de acceso y de
// acciones administrativas. Convenciones: skill `postgres-db` y
// specs/002-acceso-gestion-usuarios/data-model.md.
//
// SOLO inserción y consulta: el registro es de solo inserción (FR-025). No hay
// sentencias de modificación ni de borrado sobre `login_events`/`admin_actions`
// en ningún PR.
//
// Los campos derivados del contrato se resuelven con `LEFT JOIN users` (F-01):
// no se guardan duplicados en el registro. El `LEFT JOIN` trae `user_email` /
// `actor_email` y las partes del nombre (`*_first_name` / `*_last_name`), todas
// anulables; el `repository.go` compone `userName`/`actorName` como
// `firstName lastName` (mapRow, §8.1.6). Se devuelven las partes —y no una
// columna concatenada— para que sqlc infiera `pgtype.Text` anulable: sqlc
// tipa mal las expresiones `||`/`CASE`/`NULLIF` sobre `LEFT JOIN` (`interface{}`,
// `string` no anulable o `bool`).
// Cuando el intento no tiene cuenta asociada, el `LEFT JOIN` deja esas columnas
// en NULL (nunca se guarda ni se muestra el correo probado, FR-026).
//
// Filtro por rango de fechas: semirango `[from, to)` — `created_at >= from` y
// `created_at < to` (FR-024). `from`/`to` son opcionales (`narg` NULL = sin cota).
// Una fila por intento (éxito o fallo). `user_id` NULL cuando el correo no
// corresponde a ninguna cuenta: se registra el intento sin asociarlo ni crear
// nada (FR-003/FR-022).
func (q *Queries) InsertLoginEvent(ctx context.Context, arg InsertLoginEventParams) (InsertLoginEventRow, error) {
	row := q.db.QueryRow(ctx, insertLoginEvent, arg.UserID, arg.Result, arg.Ip)
	var i InsertLoginEventRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Result,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminActions = `-- name: ListAdminActions :many
SELECT aa.id,
       aa.actor_user_id,
       u.email AS actor_email,
       u.first_name AS actor_first_name,
       u.last_name AS actor_last_name,
       aa.action,
       aa.target_kind,
       COALESCE(aa.target_user_id, aa.target_role_id) AS target_id,
       aa.target_label,
       aa.result,
       aa.created_at
FROM admin_actions aa
LEFT JOIN users u ON u.id = aa.actor_user_id
WHERE (
        $1::uuid IS NULL
        OR aa.actor_user_id = $1
        OR aa.target_user_id = $1
      )
  AND ($2::timestamptz IS NULL OR aa.created_at >= $2)
  AND ($3::timestamptz IS NULL OR aa.created_at < $3)
ORDER BY aa.created_at DESC, aa.id DESC
LIMIT $5 OFFSET $4
`

type ListAdminActionsParams struct {
	UserID pgtype.UUID
	From   pgtype.Timestamptz
	To     pgtype.Timestamptz
	Off    int32
	Lim    int32
}

type ListAdminActionsRow struct {
	ID             pgtype.UUID
	ActorUserID    pgtype.UUID
	ActorEmail     pgtype.Text
	ActorFirstName pgtype.Text
	ActorLastName  pgtype.Text
	Action         string
	TargetKind     string
	TargetID       pgtype.UUID
	TargetLabel    pgtype.Text
	Result         string
	CreatedAt      pgtype.Timestamptz
}

// Filtro `userId`: cuenta **involucrada** — la que hizo la acción (`actor_user_id`)
// o la cuenta objetivo (`target_user_id`). La inicialización del sistema encaja
// por su `target_user_id`.
func (q *Queries) ListAdminActions(ctx context.Context, arg ListAdminActionsParams) ([]ListAdminActionsRow, error) {
	rows, err := q.db.Query(ctx, listAdminActions,
		arg.UserID,
		arg.From,
		arg.To,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminActionsRow
	for rows.Next() {
		var i ListAdminActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorFirstName,
			&i.ActorLastName,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.TargetLabel,
			&i.Result,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoginEvents = `-- name: ListLoginEvents :many
SELECT le.id,
       le.user_id,
       u.email AS user_email,
       u.first_name AS user_first_name,
       u.last_name AS user_last_name,
       le.result,
       le.ip,
       le.created_at
FROM login_events le
LEFT JOIN users u ON u.id = le.user_id
WHERE ($1::uuid IS NULL OR le.user_id = $1)
  AND ($2::timestamptz IS NULL OR le.created_at >= $2)
  AND ($3::timestamptz IS NULL OR le.created_at < $3)
ORDER BY le.created_at DESC, le.id DESC
LIMIT $5 OFFSET $4
`

type ListLoginEventsParams struct {
	UserID pgtype.UUID
	From   pgtype.Timestamptz
	To     pgtype.Timestamptz
	Off    int32
	Lim    int32
}

type ListLoginEventsRow struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	UserEmail     pgtype.Text
	UserFirstName pgtype.Text
	UserLastName  pgtype.Text
	Result        string
	Ip            string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListLoginEvents(ctx context.Context, arg ListLoginEventsParams) ([]ListLoginEventsRow, error) {
	rows, err := q.db.Query(ctx, listLoginEvents,
		arg.UserID,
		arg.From,
		arg.To,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoginEventsRow
	for rows.Next() {
		var i ListLoginEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserFirstName,
			&i.UserLastName,
			&i.Result,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
