// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: home.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHomeService = `-- name: DeleteHomeService :execrows
DELETE FROM home_services
WHERE id = $1
`

func (q *Queries) DeleteHomeService(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHomeService, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHomeSocialLink = `-- name: DeleteHomeSocialLink :execrows
DELETE FROM home_social_links
WHERE id = $1
`

func (q *Queries) DeleteHomeSocialLink(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHomeSocialLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHomeWhatsappChannel = `-- name: DeleteHomeWhatsappChannel :execrows
DELETE FROM home_whatsapp_channels
WHERE id = $1
`

func (q *Queries) DeleteHomeWhatsappChannel(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHomeWhatsappChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHomeAbout = `-- name: GetHomeAbout :one
SELECT id, singleton, text_es, text_en, publication_state, created_at, updated_at
FROM home_about
WHERE singleton
LIMIT 1
`

func (q *Queries) GetHomeAbout(ctx context.Context) (HomeAbout, error) {
	row := q.db.QueryRow(ctx, getHomeAbout)
	var i HomeAbout
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.TextEs,
		&i.TextEn,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeAboutPublished = `-- name: GetHomeAboutPublished :one
SELECT id, singleton, text_es, text_en, publication_state, created_at, updated_at
FROM home_about
WHERE singleton AND publication_state = 'published'
LIMIT 1
`

func (q *Queries) GetHomeAboutPublished(ctx context.Context) (HomeAbout, error) {
	row := q.db.QueryRow(ctx, getHomeAboutPublished)
	var i HomeAbout
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.TextEs,
		&i.TextEn,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeContact = `-- name: GetHomeContact :one
SELECT id, singleton, address_es, address_en, email, phone,
       publication_state, created_at, updated_at
FROM home_contact
WHERE singleton
LIMIT 1
`

func (q *Queries) GetHomeContact(ctx context.Context) (HomeContact, error) {
	row := q.db.QueryRow(ctx, getHomeContact)
	var i HomeContact
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.AddressEs,
		&i.AddressEn,
		&i.Email,
		&i.Phone,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeContactPublished = `-- name: GetHomeContactPublished :one
SELECT id, singleton, address_es, address_en, email, phone,
       publication_state, created_at, updated_at
FROM home_contact
WHERE singleton AND publication_state = 'published'
LIMIT 1
`

func (q *Queries) GetHomeContactPublished(ctx context.Context) (HomeContact, error) {
	row := q.db.QueryRow(ctx, getHomeContactPublished)
	var i HomeContact
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.AddressEs,
		&i.AddressEn,
		&i.Email,
		&i.Phone,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeIdentity = `-- name: GetHomeIdentity :one
SELECT id, singleton, name_es, name_en, tagline_es, tagline_en,
       mission_es, mission_en, vision_es, vision_en,
       logo_file, logo_alt_es, logo_alt_en,
       cover_image_file, cover_image_alt_es, cover_image_alt_en,
       publication_state, created_at, updated_at
FROM home_identity
WHERE singleton
LIMIT 1
`

// Panel: devuelve el singleton aunque esté en borrador.
func (q *Queries) GetHomeIdentity(ctx context.Context) (HomeIdentity, error) {
	row := q.db.QueryRow(ctx, getHomeIdentity)
	var i HomeIdentity
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.NameEs,
		&i.NameEn,
		&i.TaglineEs,
		&i.TaglineEn,
		&i.MissionEs,
		&i.MissionEn,
		&i.VisionEs,
		&i.VisionEn,
		&i.LogoFile,
		&i.LogoAltEs,
		&i.LogoAltEn,
		&i.CoverImageFile,
		&i.CoverImageAltEs,
		&i.CoverImageAltEn,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeIdentityPublished = `-- name: GetHomeIdentityPublished :one
SELECT id, singleton, name_es, name_en, tagline_es, tagline_en,
       mission_es, mission_en, vision_es, vision_en,
       logo_file, logo_alt_es, logo_alt_en,
       cover_image_file, cover_image_alt_es, cover_image_alt_en,
       publication_state, created_at, updated_at
FROM home_identity
WHERE singleton AND publication_state = 'published'
LIMIT 1
`

// Público: solo el singleton publicado (FR-013); en borrador no devuelve fila.
func (q *Queries) GetHomeIdentityPublished(ctx context.Context) (HomeIdentity, error) {
	row := q.db.QueryRow(ctx, getHomeIdentityPublished)
	var i HomeIdentity
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.NameEs,
		&i.NameEn,
		&i.TaglineEs,
		&i.TaglineEn,
		&i.MissionEs,
		&i.MissionEn,
		&i.VisionEs,
		&i.VisionEn,
		&i.LogoFile,
		&i.LogoAltEs,
		&i.LogoAltEn,
		&i.CoverImageFile,
		&i.CoverImageAltEs,
		&i.CoverImageAltEn,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeServiceByID = `-- name: GetHomeServiceByID :one
SELECT id, day_of_week, start_time, end_time, name_es, name_en,
       description_es, description_en, place_es, place_en,
       publication_state, sort_order, created_at, updated_at
FROM home_services
WHERE id = $1
`

func (q *Queries) GetHomeServiceByID(ctx context.Context, id pgtype.UUID) (HomeService, error) {
	row := q.db.QueryRow(ctx, getHomeServiceByID, id)
	var i HomeService
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.NameEs,
		&i.NameEn,
		&i.DescriptionEs,
		&i.DescriptionEn,
		&i.PlaceEs,
		&i.PlaceEn,
		&i.PublicationState,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeSocialLinkByID = `-- name: GetHomeSocialLinkByID :one
SELECT id, network, url, publication_state, created_at, updated_at
FROM home_social_links
WHERE id = $1
`

func (q *Queries) GetHomeSocialLinkByID(ctx context.Context, id pgtype.UUID) (HomeSocialLink, error) {
	row := q.db.QueryRow(ctx, getHomeSocialLinkByID, id)
	var i HomeSocialLink
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.Url,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeWhatsappChannelByID = `-- name: GetHomeWhatsappChannelByID :one
SELECT id, kind, destination, name_es, name_en, publication_state, sort_order,
       created_at, updated_at
FROM home_whatsapp_channels
WHERE id = $1
`

func (q *Queries) GetHomeWhatsappChannelByID(ctx context.Context, id pgtype.UUID) (HomeWhatsappChannel, error) {
	row := q.db.QueryRow(ctx, getHomeWhatsappChannelByID, id)
	var i HomeWhatsappChannel
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Destination,
		&i.NameEs,
		&i.NameEn,
		&i.PublicationState,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHomeService = `-- name: InsertHomeService :one

INSERT INTO home_services (
    day_of_week, start_time, end_time, name_es, name_en,
    description_es, description_en, place_es, place_en,
    publication_state, sort_order
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11
)
RETURNING id, day_of_week, start_time, end_time, name_es, name_en,
          description_es, description_en, place_es, place_en,
          publication_state, sort_order, created_at, updated_at
`

type InsertHomeServiceParams struct {
	DayOfWeek        int16
	StartTime        string
	EndTime          pgtype.Text
	NameEs           string
	NameEn           pgtype.Text
	DescriptionEs    pgtype.Text
	DescriptionEn    pgtype.Text
	PlaceEs          string
	PlaceEn          pgtype.Text
	PublicationState string
	SortOrder        int32
}

// --------------------------------------------------------- horario (servicios)
func (q *Queries) InsertHomeService(ctx context.Context, arg InsertHomeServiceParams) (HomeService, error) {
	row := q.db.QueryRow(ctx, insertHomeService,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.NameEs,
		arg.NameEn,
		arg.DescriptionEs,
		arg.DescriptionEn,
		arg.PlaceEs,
		arg.PlaceEn,
		arg.PublicationState,
		arg.SortOrder,
	)
	var i HomeService
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.NameEs,
		&i.NameEn,
		&i.DescriptionEs,
		&i.DescriptionEn,
		&i.PlaceEs,
		&i.PlaceEn,
		&i.PublicationState,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHomeSocialLink = `-- name: InsertHomeSocialLink :one

INSERT INTO home_social_links (network, url, publication_state)
VALUES ($1, $2, $3)
RETURNING id, network, url, publication_state, created_at, updated_at
`

type InsertHomeSocialLinkParams struct {
	Network          string
	Url              string
	PublicationState string
}

// ----------------------------------------------------------------- redes
func (q *Queries) InsertHomeSocialLink(ctx context.Context, arg InsertHomeSocialLinkParams) (HomeSocialLink, error) {
	row := q.db.QueryRow(ctx, insertHomeSocialLink, arg.Network, arg.Url, arg.PublicationState)
	var i HomeSocialLink
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.Url,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHomeWhatsappChannel = `-- name: InsertHomeWhatsappChannel :one

INSERT INTO home_whatsapp_channels (
    name_es, name_en, kind, destination, publication_state, sort_order
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, kind, destination, name_es, name_en, publication_state, sort_order,
          created_at, updated_at
`

type InsertHomeWhatsappChannelParams struct {
	NameEs           string
	NameEn           pgtype.Text
	Kind             string
	Destination      string
	PublicationState string
	SortOrder        int32
}

// ------------------------------------------------- canales de WhatsApp
func (q *Queries) InsertHomeWhatsappChannel(ctx context.Context, arg InsertHomeWhatsappChannelParams) (HomeWhatsappChannel, error) {
	row := q.db.QueryRow(ctx, insertHomeWhatsappChannel,
		arg.NameEs,
		arg.NameEn,
		arg.Kind,
		arg.Destination,
		arg.PublicationState,
		arg.SortOrder,
	)
	var i HomeWhatsappChannel
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Destination,
		&i.NameEs,
		&i.NameEn,
		&i.PublicationState,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isHomeFilePublished = `-- name: IsHomeFilePublished :one

SELECT EXISTS (
    SELECT 1
    FROM home_identity
    WHERE publication_state = 'published'
      AND $1 IN (logo_file, cover_image_file)
) AS published
`

// ---------------------------------------------------- archivos de imagen
// ¿El nombre de archivo está referenciado por contenido PUBLICADO? (analyze C4)
// `TRUE` solo si la identidad publicada lo usa como logo o imagen de portada;
// `FALSE` cuando no existe referencia, la identidad está en borrador o el
// archivo es huérfano. F4–F9 amplían esta consulta con sus tablas.
func (q *Queries) IsHomeFilePublished(ctx context.Context, fileName pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, isHomeFilePublished, fileName)
	var published bool
	err := row.Scan(&published)
	return published, err
}

const listHomeServices = `-- name: ListHomeServices :many
SELECT id, day_of_week, start_time, end_time, name_es, name_en,
       description_es, description_en, place_es, place_en,
       publication_state, sort_order, created_at, updated_at
FROM home_services
ORDER BY sort_order, id
`

// Panel: todos los servicios (borradores incluidos), orden estable.
func (q *Queries) ListHomeServices(ctx context.Context) ([]HomeService, error) {
	rows, err := q.db.Query(ctx, listHomeServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeService
	for rows.Next() {
		var i HomeService
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.NameEs,
			&i.NameEn,
			&i.DescriptionEs,
			&i.DescriptionEn,
			&i.PlaceEs,
			&i.PlaceEn,
			&i.PublicationState,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeServicesPublished = `-- name: ListHomeServicesPublished :many
SELECT id, day_of_week, start_time, end_time, name_es, name_en,
       description_es, description_en, place_es, place_en,
       publication_state, sort_order, created_at, updated_at
FROM home_services
WHERE publication_state = 'published'
ORDER BY sort_order, id
`

// Público: solo servicios publicados (FR-013).
func (q *Queries) ListHomeServicesPublished(ctx context.Context) ([]HomeService, error) {
	rows, err := q.db.Query(ctx, listHomeServicesPublished)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeService
	for rows.Next() {
		var i HomeService
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.NameEs,
			&i.NameEn,
			&i.DescriptionEs,
			&i.DescriptionEn,
			&i.PlaceEs,
			&i.PlaceEn,
			&i.PublicationState,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeSocialLinks = `-- name: ListHomeSocialLinks :many
SELECT id, network, url, publication_state, created_at, updated_at
FROM home_social_links
ORDER BY network
`

func (q *Queries) ListHomeSocialLinks(ctx context.Context) ([]HomeSocialLink, error) {
	rows, err := q.db.Query(ctx, listHomeSocialLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeSocialLink
	for rows.Next() {
		var i HomeSocialLink
		if err := rows.Scan(
			&i.ID,
			&i.Network,
			&i.Url,
			&i.PublicationState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeSocialLinksPublished = `-- name: ListHomeSocialLinksPublished :many
SELECT id, network, url, publication_state, created_at, updated_at
FROM home_social_links
WHERE publication_state = 'published'
ORDER BY network
`

func (q *Queries) ListHomeSocialLinksPublished(ctx context.Context) ([]HomeSocialLink, error) {
	rows, err := q.db.Query(ctx, listHomeSocialLinksPublished)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeSocialLink
	for rows.Next() {
		var i HomeSocialLink
		if err := rows.Scan(
			&i.ID,
			&i.Network,
			&i.Url,
			&i.PublicationState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeWhatsappChannels = `-- name: ListHomeWhatsappChannels :many
SELECT id, kind, destination, name_es, name_en, publication_state, sort_order,
       created_at, updated_at
FROM home_whatsapp_channels
ORDER BY sort_order, id
`

func (q *Queries) ListHomeWhatsappChannels(ctx context.Context) ([]HomeWhatsappChannel, error) {
	rows, err := q.db.Query(ctx, listHomeWhatsappChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeWhatsappChannel
	for rows.Next() {
		var i HomeWhatsappChannel
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Destination,
			&i.NameEs,
			&i.NameEn,
			&i.PublicationState,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeWhatsappChannelsPublished = `-- name: ListHomeWhatsappChannelsPublished :many
SELECT id, kind, destination, name_es, name_en, publication_state, sort_order,
       created_at, updated_at
FROM home_whatsapp_channels
WHERE publication_state = 'published'
ORDER BY sort_order, id
`

func (q *Queries) ListHomeWhatsappChannelsPublished(ctx context.Context) ([]HomeWhatsappChannel, error) {
	rows, err := q.db.Query(ctx, listHomeWhatsappChannelsPublished)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeWhatsappChannel
	for rows.Next() {
		var i HomeWhatsappChannel
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Destination,
			&i.NameEs,
			&i.NameEn,
			&i.PublicationState,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHomeService = `-- name: UpdateHomeService :one
UPDATE home_services
SET day_of_week       = $1,
    start_time        = $2,
    end_time          = $3,
    name_es           = $4,
    name_en           = $5,
    description_es    = $6,
    description_en    = $7,
    place_es          = $8,
    place_en          = $9,
    publication_state = $10,
    sort_order        = $11,
    updated_at        = now()
WHERE id = $12
RETURNING id, day_of_week, start_time, end_time, name_es, name_en,
          description_es, description_en, place_es, place_en,
          publication_state, sort_order, created_at, updated_at
`

type UpdateHomeServiceParams struct {
	DayOfWeek        int16
	StartTime        string
	EndTime          pgtype.Text
	NameEs           string
	NameEn           pgtype.Text
	DescriptionEs    pgtype.Text
	DescriptionEn    pgtype.Text
	PlaceEs          string
	PlaceEn          pgtype.Text
	PublicationState string
	SortOrder        int32
	ID               pgtype.UUID
}

// Reemplazo completo de los campos mutables (el service fusiona el PATCH y
// valida antes de llamar).
func (q *Queries) UpdateHomeService(ctx context.Context, arg UpdateHomeServiceParams) (HomeService, error) {
	row := q.db.QueryRow(ctx, updateHomeService,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.NameEs,
		arg.NameEn,
		arg.DescriptionEs,
		arg.DescriptionEn,
		arg.PlaceEs,
		arg.PlaceEn,
		arg.PublicationState,
		arg.SortOrder,
		arg.ID,
	)
	var i HomeService
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.NameEs,
		&i.NameEn,
		&i.DescriptionEs,
		&i.DescriptionEn,
		&i.PlaceEs,
		&i.PlaceEn,
		&i.PublicationState,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHomeSocialLink = `-- name: UpdateHomeSocialLink :one
UPDATE home_social_links
SET network           = $1,
    url               = $2,
    publication_state = $3,
    updated_at        = now()
WHERE id = $4
RETURNING id, network, url, publication_state, created_at, updated_at
`

type UpdateHomeSocialLinkParams struct {
	Network          string
	Url              string
	PublicationState string
	ID               pgtype.UUID
}

func (q *Queries) UpdateHomeSocialLink(ctx context.Context, arg UpdateHomeSocialLinkParams) (HomeSocialLink, error) {
	row := q.db.QueryRow(ctx, updateHomeSocialLink,
		arg.Network,
		arg.Url,
		arg.PublicationState,
		arg.ID,
	)
	var i HomeSocialLink
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.Url,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHomeWhatsappChannel = `-- name: UpdateHomeWhatsappChannel :one
UPDATE home_whatsapp_channels
SET name_es           = $1,
    name_en           = $2,
    kind              = $3,
    destination       = $4,
    publication_state = $5,
    sort_order        = $6,
    updated_at        = now()
WHERE id = $7
RETURNING id, kind, destination, name_es, name_en, publication_state, sort_order,
          created_at, updated_at
`

type UpdateHomeWhatsappChannelParams struct {
	NameEs           string
	NameEn           pgtype.Text
	Kind             string
	Destination      string
	PublicationState string
	SortOrder        int32
	ID               pgtype.UUID
}

func (q *Queries) UpdateHomeWhatsappChannel(ctx context.Context, arg UpdateHomeWhatsappChannelParams) (HomeWhatsappChannel, error) {
	row := q.db.QueryRow(ctx, updateHomeWhatsappChannel,
		arg.NameEs,
		arg.NameEn,
		arg.Kind,
		arg.Destination,
		arg.PublicationState,
		arg.SortOrder,
		arg.ID,
	)
	var i HomeWhatsappChannel
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Destination,
		&i.NameEs,
		&i.NameEn,
		&i.PublicationState,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHomeAbout = `-- name: UpsertHomeAbout :one

INSERT INTO home_about (text_es, text_en, publication_state)
VALUES ($1, $2, $3)
ON CONFLICT (singleton) DO UPDATE SET
    text_es           = EXCLUDED.text_es,
    text_en           = EXCLUDED.text_en,
    publication_state = EXCLUDED.publication_state,
    updated_at        = now()
RETURNING id, singleton, text_es, text_en, publication_state, created_at, updated_at
`

type UpsertHomeAboutParams struct {
	TextEs           string
	TextEn           pgtype.Text
	PublicationState string
}

// ------------------------------------------------------------- quiénes somos
func (q *Queries) UpsertHomeAbout(ctx context.Context, arg UpsertHomeAboutParams) (HomeAbout, error) {
	row := q.db.QueryRow(ctx, upsertHomeAbout, arg.TextEs, arg.TextEn, arg.PublicationState)
	var i HomeAbout
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.TextEs,
		&i.TextEn,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHomeContact = `-- name: UpsertHomeContact :one

INSERT INTO home_contact (address_es, address_en, email, phone, publication_state)
VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (singleton) DO UPDATE SET
    address_es        = EXCLUDED.address_es,
    address_en        = EXCLUDED.address_en,
    email             = EXCLUDED.email,
    phone             = EXCLUDED.phone,
    publication_state = EXCLUDED.publication_state,
    updated_at        = now()
RETURNING id, singleton, address_es, address_en, email, phone,
          publication_state, created_at, updated_at
`

type UpsertHomeContactParams struct {
	AddressEs        string
	AddressEn        pgtype.Text
	Email            string
	Phone            string
	PublicationState string
}

// -------------------------------------------------------------------- contacto
func (q *Queries) UpsertHomeContact(ctx context.Context, arg UpsertHomeContactParams) (HomeContact, error) {
	row := q.db.QueryRow(ctx, upsertHomeContact,
		arg.AddressEs,
		arg.AddressEn,
		arg.Email,
		arg.Phone,
		arg.PublicationState,
	)
	var i HomeContact
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.AddressEs,
		&i.AddressEn,
		&i.Email,
		&i.Phone,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHomeIdentity = `-- name: UpsertHomeIdentity :one


INSERT INTO home_identity (
    name_es, name_en, tagline_es, tagline_en, mission_es, mission_en,
    vision_es, vision_en, logo_file, logo_alt_es, logo_alt_en,
    cover_image_file, cover_image_alt_es, cover_image_alt_en, publication_state
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15
)
ON CONFLICT (singleton) DO UPDATE SET
    name_es            = EXCLUDED.name_es,
    name_en            = EXCLUDED.name_en,
    tagline_es         = EXCLUDED.tagline_es,
    tagline_en         = EXCLUDED.tagline_en,
    mission_es         = EXCLUDED.mission_es,
    mission_en         = EXCLUDED.mission_en,
    vision_es          = EXCLUDED.vision_es,
    vision_en          = EXCLUDED.vision_en,
    logo_file          = EXCLUDED.logo_file,
    logo_alt_es        = EXCLUDED.logo_alt_es,
    logo_alt_en        = EXCLUDED.logo_alt_en,
    cover_image_file   = EXCLUDED.cover_image_file,
    cover_image_alt_es = EXCLUDED.cover_image_alt_es,
    cover_image_alt_en = EXCLUDED.cover_image_alt_en,
    publication_state  = EXCLUDED.publication_state,
    updated_at         = now()
RETURNING id, singleton, name_es, name_en, tagline_es, tagline_en,
          mission_es, mission_en, vision_es, vision_en,
          logo_file, logo_alt_es, logo_alt_en,
          cover_image_file, cover_image_alt_es, cover_image_alt_en,
          publication_state, created_at, updated_at
`

type UpsertHomeIdentityParams struct {
	NameEs           string
	NameEn           pgtype.Text
	TaglineEs        pgtype.Text
	TaglineEn        pgtype.Text
	MissionEs        pgtype.Text
	MissionEn        pgtype.Text
	VisionEs         pgtype.Text
	VisionEn         pgtype.Text
	LogoFile         pgtype.Text
	LogoAltEs        pgtype.Text
	LogoAltEn        pgtype.Text
	CoverImageFile   pgtype.Text
	CoverImageAltEs  pgtype.Text
	CoverImageAltEn  pgtype.Text
	PublicationState string
}

// Consultas del contenido de la portada (F3): identidad, «quiénes somos»,
// contacto, horario de servicios, canales de WhatsApp y redes sociales.
// Convenciones: skill `postgres-db` y
// specs/003-portada-info-general/data-model.md (fuente de verdad).
//
// Columnas listadas explícitamente (sin `SELECT *`), parámetros nombrados
// (`sqlc.arg`) y `ORDER BY` determinista: `sort_order, id` en las colecciones
// ordenables y `network` en redes (§8.1.7).
//
// Variantes `…Published`: son la ÚNICA vía pública (P3-4/FR-013); la variante
// sin sufijo es la del panel (exige el permiso `portada`) y es la única que
// devuelve borradores. Los singletons llevan `singleton BOOLEAN` + `UNIQUE` y
// el upsert va en transacción con `pg_advisory_xact_lock` (R3-4, lo toma el
// repository de T314, no esta consulta).
//
// La auditoría NO se define aquí: se reutiliza `InsertAdminAction` de
// `queries/audit.sql` dentro de la transacción de cada mutación (R3-11).
// ------------------------------------------------------------------ identidad
// Crea o reemplaza el singleton de identidad (UNIQUE (singleton)).
func (q *Queries) UpsertHomeIdentity(ctx context.Context, arg UpsertHomeIdentityParams) (HomeIdentity, error) {
	row := q.db.QueryRow(ctx, upsertHomeIdentity,
		arg.NameEs,
		arg.NameEn,
		arg.TaglineEs,
		arg.TaglineEn,
		arg.MissionEs,
		arg.MissionEn,
		arg.VisionEs,
		arg.VisionEn,
		arg.LogoFile,
		arg.LogoAltEs,
		arg.LogoAltEn,
		arg.CoverImageFile,
		arg.CoverImageAltEs,
		arg.CoverImageAltEn,
		arg.PublicationState,
	)
	var i HomeIdentity
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.NameEs,
		&i.NameEn,
		&i.TaglineEs,
		&i.TaglineEn,
		&i.MissionEs,
		&i.MissionEn,
		&i.VisionEs,
		&i.VisionEn,
		&i.LogoFile,
		&i.LogoAltEs,
		&i.LogoAltEn,
		&i.CoverImageFile,
		&i.CoverImageAltEs,
		&i.CoverImageAltEn,
		&i.PublicationState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
