// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAction struct {
	ID           pgtype.UUID
	ActorUserID  pgtype.UUID
	Action       string
	TargetKind   string
	TargetUserID pgtype.UUID
	TargetRoleID pgtype.UUID
	TargetLabel  pgtype.Text
	Result       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type HomeAbout struct {
	ID               pgtype.UUID
	Singleton        bool
	TextEs           string
	TextEn           pgtype.Text
	PublicationState string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type HomeContact struct {
	ID               pgtype.UUID
	Singleton        bool
	AddressEs        string
	AddressEn        pgtype.Text
	Email            string
	Phone            string
	PublicationState string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type HomeIdentity struct {
	ID               pgtype.UUID
	Singleton        bool
	NameEs           string
	NameEn           pgtype.Text
	TaglineEs        pgtype.Text
	TaglineEn        pgtype.Text
	MissionEs        pgtype.Text
	MissionEn        pgtype.Text
	VisionEs         pgtype.Text
	VisionEn         pgtype.Text
	LogoFile         pgtype.Text
	LogoAltEs        pgtype.Text
	LogoAltEn        pgtype.Text
	CoverImageFile   pgtype.Text
	CoverImageAltEs  pgtype.Text
	CoverImageAltEn  pgtype.Text
	PublicationState string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type HomeService struct {
	ID               pgtype.UUID
	DayOfWeek        int16
	StartTime        string
	EndTime          pgtype.Text
	NameEs           string
	NameEn           pgtype.Text
	DescriptionEs    pgtype.Text
	DescriptionEn    pgtype.Text
	PlaceEs          string
	PlaceEn          pgtype.Text
	PublicationState string
	SortOrder        int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type HomeSocialLink struct {
	ID               pgtype.UUID
	Network          string
	Url              string
	PublicationState string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type HomeWhatsappChannel struct {
	ID               pgtype.UUID
	Kind             string
	Destination      string
	NameEs           string
	NameEn           pgtype.Text
	PublicationState string
	SortOrder        int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type LoginEvent struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Result    string
	Ip        string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Permission struct {
	ID        pgtype.UUID
	Code      string
	Label     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Role struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RolePermission struct {
	ID           pgtype.UUID
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	Email              string
	FirstName          string
	LastName           string
	Phone              string
	PasswordHash       string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastLoginAt        pgtype.Timestamptz
	LastLoginIp        pgtype.Text
}
