// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAction struct {
	ID           pgtype.UUID
	ActorUserID  pgtype.UUID
	Action       string
	TargetKind   string
	TargetUserID pgtype.UUID
	TargetRoleID pgtype.UUID
	TargetLabel  pgtype.Text
	Result       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type LoginEvent struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Result    string
	Ip        string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Permission struct {
	ID        pgtype.UUID
	Code      string
	Label     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Role struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RolePermission struct {
	ID           pgtype.UUID
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	Email              string
	FirstName          string
	LastName           string
	Phone              string
	PasswordHash       string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastLoginAt        pgtype.Timestamptz
	LastLoginIp        pgtype.Text
}
