// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPermissionIDsByCodes = `-- name: GetPermissionIDsByCodes :many
SELECT id, code
FROM permissions
WHERE code = ANY($1::text[])
ORDER BY code ASC
`

type GetPermissionIDsByCodesRow struct {
	ID   pgtype.UUID
	Code string
}

// Devuelve el par (id, code) de cada código presente en el catálogo. Devolver
// también `code` permite al service distinguir qué códigos no existen (400 con
// `details`) al crear/editar roles; el `id` es lo que se inserta en
// `role_permissions`. Códigos repetidos no duplican filas.
func (q *Queries) GetPermissionIDsByCodes(ctx context.Context, codes []string) ([]GetPermissionIDsByCodesRow, error) {
	rows, err := q.db.Query(ctx, getPermissionIDsByCodes, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPermissionIDsByCodesRow
	for rows.Next() {
		var i GetPermissionIDsByCodesRow
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many

SELECT id, code, label, created_at, updated_at
FROM permissions
ORDER BY code ASC
`

// Consultas del catálogo de permisos (FR-015).
// Convenciones: skill `postgres-db` y specs/002-acceso-gestion-usuarios/data-model.md.
// Columnas listadas explícitamente (sin comodines), parámetros $1…$n y ORDER BY determinista.
func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
