// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoleUsers = `-- name: CountRoleUsers :one
SELECT count(*)::bigint AS total
FROM users
WHERE role_id = $1
`

// Cuentas asignadas al rol: `0` = el rol se puede eliminar (FR-017).
func (q *Queries) CountRoleUsers(ctx context.Context, roleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleUsers, roleID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countRoles = `-- name: CountRoles :one
SELECT count(*)::bigint AS total
FROM roles
`

func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles
WHERE id = $1
`

// Solo llega aquí un rol sin cuentas asignadas (FR-017); el `ON DELETE RESTRICT`
// de `users.role_id` es la red de seguridad. `role_permissions` cae en cascada.
func (q *Queries) DeleteRole(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

// Borra los permisos actuales del rol; el service reinserta el conjunto nuevo en
// la misma transacción (un rol conserva ≥ 1 permiso, FR-014).
func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT r.id,
       r.name,
       r.created_at,
       r.updated_at,
       COALESCE((
           SELECT array_agg(p.code ORDER BY p.code)
           FROM role_permissions rp
           JOIN permissions p ON p.id = rp.permission_id
           WHERE rp.role_id = r.id
       ), '{}')::text[] AS permissions,
       (SELECT count(*) FROM users u WHERE u.role_id = r.id)::bigint AS user_count
FROM roles r
WHERE r.id = $1
`

type GetRoleByIDRow struct {
	ID          pgtype.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Permissions []string
	UserCount   int64
}

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (GetRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i GetRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Permissions,
		&i.UserCount,
	)
	return i, err
}

const getRoleByNameLower = `-- name: GetRoleByNameLower :one
SELECT id, name, created_at, updated_at
FROM roles
WHERE lower(name) = lower(btrim($1))
LIMIT 1
`

// Unicidad normalizada (Q5): dos nombres que solo difieren en mayúsculas (o en
// espacios sobrantes en los extremos) son el mismo rol. El service normaliza el
// nombre antes de llamar; `btrim` aquí es la red de seguridad.
func (q *Queries) GetRoleByNameLower(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByNameLower, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRole = `-- name: InsertRole :one

INSERT INTO roles (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

// Consultas de roles y su relación con el catálogo de permisos (FR-014, FR-017).
// Convenciones: skill `postgres-db` y specs/002-acceso-gestion-usuarios/data-model.md.
// Columnas listadas explícitamente (sin comodines), parámetros $1…$n y ORDER BY determinista.
// `ListRoles`/`GetRoleByID` embeben los códigos de permiso y el recuento de cuentas
// que usan el rol (FR-017) para servir `RoleItem` sin consultas N+1.
func (q *Queries) InsertRole(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, insertRole, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
`

type InsertRolePermissionParams struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const listRoles = `-- name: ListRoles :many
SELECT r.id,
       r.name,
       r.created_at,
       r.updated_at,
       COALESCE((
           SELECT array_agg(p.code ORDER BY p.code)
           FROM role_permissions rp
           JOIN permissions p ON p.id = rp.permission_id
           WHERE rp.role_id = r.id
       ), '{}')::text[] AS permissions,
       (SELECT count(*) FROM users u WHERE u.role_id = r.id)::bigint AS user_count
FROM roles r
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2 OFFSET $1
`

type ListRolesParams struct {
	Off int32
	Lim int32
}

type ListRolesRow struct {
	ID          pgtype.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Permissions []string
	UserCount   int64
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Permissions,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminGuard = `-- name: LockAdminGuard :exec
SELECT pg_advisory_xact_lock(726112001)
`

// Cerradura de asesoramiento transaccional (P7). Clave FIJA y compartida por el
// guard anti-bloqueo (FR-008) y la inicialización única (FR-007): serializa las
// mutaciones que podrían dejar el panel sin administración. Se libera al cerrar
// la transacción. No cambiar el valor sin coordinarlo con esas rutas.
func (q *Queries) LockAdminGuard(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAdminGuard)
	return err
}

const updateRoleName = `-- name: UpdateRoleName :one
UPDATE roles
SET name = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, name, created_at, updated_at
`

type UpdateRoleNameParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRoleName, arg.Name, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
