// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*)::bigint AS total
FROM users u
WHERE u.is_active
  AND EXISTS (
      SELECT 1
      FROM role_permissions rp
      JOIN permissions p ON p.id = rp.permission_id
      WHERE rp.role_id = u.role_id
        AND p.code = 'admin_usuarios_roles'
  )
`

// Recuento post-mutación del guard anti-bloqueo (FR-008/P7): cuentas activas cuyo
// rol concede `admin_usuarios_roles`. `admin_usuarios_roles` es un `code` estable
// y sembrado por la migración 000002.
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint AS total
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT count(*)::bigint AS total
FROM users
WHERE role_id = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, roleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, roleID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUserAuthByEmail = `-- name: GetUserAuthByEmail :one
SELECT u.id,
       u.email,
       u.first_name,
       u.last_name,
       u.password_hash,
       u.must_change_password,
       u.is_active,
       u.role_id,
       r.name AS role_name,
       COALESCE((
           SELECT array_agg(p.code ORDER BY p.code)
           FROM role_permissions rp
           JOIN permissions p ON p.id = rp.permission_id
           WHERE rp.role_id = u.role_id
       ), '{}')::text[] AS permissions
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.email = $1
`

type GetUserAuthByEmailRow struct {
	ID                 pgtype.UUID
	Email              string
	FirstName          string
	LastName           string
	PasswordHash       string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
	RoleName           string
	Permissions        []string
}

// Para login y `authn`: credenciales de la cuenta (hash y estado) + su rol y los
// códigos de permiso efectivos (FR-018). El hash nunca sale del repository como
// DTO (§IV, FR-003); `permissions` vacío es `{}`, nunca NULL.
func (q *Queries) GetUserAuthByEmail(ctx context.Context, email string) (GetUserAuthByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByEmail, email)
	var i GetUserAuthByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.IsActive,
		&i.RoleID,
		&i.RoleName,
		&i.Permissions,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id,
       u.email,
       u.first_name,
       u.last_name,
       u.phone,
       u.must_change_password,
       u.is_active,
       u.role_id,
       r.name AS role_name,
       u.last_login_at,
       u.last_login_ip,
       u.created_at,
       u.updated_at
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.email = $1
`

type GetUserByEmailRow struct {
	ID                 pgtype.UUID
	Email              string
	FirstName          string
	LastName           string
	Phone              string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
	RoleName           string
	LastLoginAt        pgtype.Timestamptz
	LastLoginIp        pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// El correo se guarda normalizado (Q5) y el service normaliza la entrada; la
// igualdad exacta usa el índice `UNIQUE` de `email`.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.MustChangePassword,
		&i.IsActive,
		&i.RoleID,
		&i.RoleName,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id,
       u.email,
       u.first_name,
       u.last_name,
       u.phone,
       u.must_change_password,
       u.is_active,
       u.role_id,
       r.name AS role_name,
       u.last_login_at,
       u.last_login_ip,
       u.created_at,
       u.updated_at
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID                 pgtype.UUID
	Email              string
	FirstName          string
	LastName           string
	Phone              string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
	RoleName           string
	LastLoginAt        pgtype.Timestamptz
	LastLoginIp        pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// `JOIN roles` (no `LEFT`): `users.role_id` es NOT NULL con FK, siempre hay rol.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.MustChangePassword,
		&i.IsActive,
		&i.RoleID,
		&i.RoleName,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one

INSERT INTO users (
    email,
    first_name,
    last_name,
    phone,
    password_hash,
    must_change_password,
    is_active,
    role_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, email, first_name, last_name, phone, must_change_password, is_active,
          role_id, last_login_at, last_login_ip, created_at, updated_at
`

type InsertUserParams struct {
	Email              string
	FirstName          string
	LastName           string
	Phone              string
	PasswordHash       string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
}

type InsertUserRow struct {
	ID                 pgtype.UUID
	Email              string
	FirstName          string
	LastName           string
	Phone              string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
	LastLoginAt        pgtype.Timestamptz
	LastLoginIp        pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// Consultas de cuentas del panel (FR-009…FR-013, FR-017, FR-019, FR-021).
// Convenciones: skill `postgres-db` y specs/002-acceso-gestion-usuarios/data-model.md.
// Columnas listadas explícitamente (sin comodines), parámetros $1…$n, ORDER BY determinista
// (`created_at DESC, id DESC`, §8.1.7) y LIMIT/OFFSET en los listados.
// NO existe `DELETE` sobre `users`: retirar acceso es `is_active = false` (FR-013).
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.IsActive,
		arg.RoleID,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.MustChangePassword,
		&i.IsActive,
		&i.RoleID,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id,
       u.email,
       u.first_name,
       u.last_name,
       u.phone,
       u.must_change_password,
       u.is_active,
       u.role_id,
       r.name AS role_name,
       u.last_login_at,
       u.last_login_ip,
       u.created_at,
       u.updated_at
FROM users u
JOIN roles r ON r.id = u.role_id
ORDER BY u.created_at DESC, u.id DESC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	Off int32
	Lim int32
}

type ListUsersRow struct {
	ID                 pgtype.UUID
	Email              string
	FirstName          string
	LastName           string
	Phone              string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
	RoleName           string
	LastLoginAt        pgtype.Timestamptz
	LastLoginIp        pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.MustChangePassword,
			&i.IsActive,
			&i.RoleID,
			&i.RoleName,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserMustChangePassword = `-- name: SetUserMustChangePassword :exec
UPDATE users
SET must_change_password = $1,
    updated_at = now()
WHERE id = $2
`

type SetUserMustChangePasswordParams struct {
	MustChangePassword bool
	ID                 pgtype.UUID
}

func (q *Queries) SetUserMustChangePassword(ctx context.Context, arg SetUserMustChangePasswordParams) error {
	_, err := q.db.Exec(ctx, setUserMustChangePassword, arg.MustChangePassword, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $1,
    first_name = $2,
    last_name = $3,
    phone = $4,
    role_id = $5,
    is_active = $6,
    updated_at = now()
WHERE id = $7
RETURNING id, email, first_name, last_name, phone, must_change_password, is_active,
          role_id, last_login_at, last_login_ip, created_at, updated_at
`

type UpdateUserParams struct {
	Email     string
	FirstName string
	LastName  string
	Phone     string
	RoleID    pgtype.UUID
	IsActive  bool
	ID        pgtype.UUID
}

type UpdateUserRow struct {
	ID                 pgtype.UUID
	Email              string
	FirstName          string
	LastName           string
	Phone              string
	MustChangePassword bool
	IsActive           bool
	RoleID             pgtype.UUID
	LastLoginAt        pgtype.Timestamptz
	LastLoginIp        pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// Edita datos, rol y estado (FR-011); `email` normalizado por el service (Q5).
// `RETURNING` no puede traer `role_name` de `roles`: el service relee con
// `GetUserByID` cuando necesita el `UserItem` completo.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.RoleID,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.MustChangePassword,
		&i.IsActive,
		&i.RoleID,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = $1,
    last_login_ip = $2,
    updated_at = now()
WHERE id = $3
`

type UpdateUserLastLoginParams struct {
	LastLoginAt pgtype.Timestamptz
	LastLoginIp pgtype.Text
	ID          pgtype.UUID
}

// Proyección del último acceso exitoso (FR-021); SOLO la escribe el login exitoso,
// junto con su fila de `login_events`. Ninguna vía de API la acepta como entrada.
func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.LastLoginAt, arg.LastLoginIp, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           pgtype.UUID
}

// Solo el hash (bcrypt, §IV). El flag de cambio obligatorio se maneja aparte con
// `SetUserMustChangePassword`, para distinguir el restablecimiento por un
// administrador del cambio propio (FR-020).
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
